name: Release it
on:
  push:
    branches:
      - main # or master

permissions:
  contents: write # for checkout
  issues: write
  pull-requests: write # to be able to comment on released pull requests

jobs:
  release:
    uses: jorkab/gha-shared/.github/workflows/release-it.yml@v1
    secrets:
      release-token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
